name: "caddy-blade_2016"

services:
  caddy:
    container_name: caddy-blade_2016
    env_file:
      - .env
    volumes:
      - ./${CADDY_INSTANCE:-caddy}/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/data:/data
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/config:/config
    labels:
      - homepage.name=Caddy Blade-2016
      - homepage.description=Blade-2016 Reverse Proxy
      - homepage.widget.url=http://${HOST_NAME}.${TAILNET}:${PORT_CADDY_ADMIN}