max_connections = 25
superuser_reserved_connections = 3

shared_buffers = 32MB
work_mem = 2MB
maintenance_work_mem = 16MB
huge_pages = off

wal_buffers = 4MB
min_wal_size = 80MB
max_wal_size = 256MB
checkpoint_completion_target = 0.9

effective_cache_size = 128MB
random_page_cost = 1.1
effective_io_concurrency = 100

max_worker_processes = 2
max_parallel_workers = 2
max_parallel_workers_per_gather = 1
max_parallel_maintenance_workers = 1

autovacuum = on
autovacuum_max_workers = 1
autovacuum_vacuum_cost_delay = 20ms

log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 500
log_line_prefix = '%t [%p] %u@%d '

dynamic_shared_memory_type = posix

listen_addresses = '*'
hba_file = '/etc/postgresql/pg_hba.conf'
