name: "caddy-pi_rack_1"

services:
  caddy:
    container_name: caddy-pi_rack_1
    env_file:
      - .env
    volumes:
      - ./${CADDY_INSTANCE:-caddy}/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./${CADDY_INSTANCE:-caddy}/config/data/tesla.pem:/srv/.well-known/appspecific/com.tesla.3p.public-key.pem:ro
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/data:/data
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/config:/config
    labels:
      - homepage.name=Caddy Home
      - homepage.description=Home Reverse Proxy
      - homepage.widget.url=http://${HOST_NAME}.${TAILNET}:${PORT_CADDY_ADMIN}