[[stack]]
name = "immich"
tags = ["media", "photos"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "simtel12"
repo = "simtel12/komodo-app-stacks"
branch = "main"
reclone = false
run_directory = "services/immich"
file_paths = [
    "docker-compose.yaml"
]

environment = """
# System configuration
TZ=[[TZ]]

# Version configuration
IMMICH_TAG=release

# Network and domain configuration
DOMAIN=[[OP__KOMODO__COMMON__DOMAIN]]
TAILNET=[[OP__KOMODO__COMMON__TAILNET]]
PORT_IMMICH_HTTP=[[PORT_IMMICH_HTTP]]

# Database configuration
DB_DATABASE_NAME=immich
DB_USERNAME=postgres
DB_PASSWORD=[[OP__KOMODO__IMMICH__IMMICH_DB_PASSWORD]]

# API tokens
IMMICH_API_AUTH_TOKEN=[[OP__KOMODO__IMMICH__IMMICH_API_AUTH_TOKEN]]

# Storage configuration
NAS_IP=[[OP__KOMODO__COMMON__HOME_NAS_IP]]
DB_DATA_LOCATION=[[CONFIG_DIR]]/immich/postgres
"""