[[stack]]
name = "monitoring-agent"
tags = ["monitoring", "beszel", "agent"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
destroy_before_deploy = false
git_account = "simtel12"
repo = "simtel12/komodo-app-stacks"
branch = "main"
reclone = false
file_paths = [
    "services/monitoring-agent/docker-compose.yaml",
]

environment = """
# Network configuration
PORT_BESZEL_LISTEN=[[OP__KOMODO__MONITORING__PORT_BESZEL_LISTEN]]

# Authentication
BESZEL_AGENT_KEY=[[OP__KOMODO__MONITORING__BESZEL_AGENT_KEY]]
"""