name: "ghostfolio"

services:
  ghostfolio:
    container_name: ghostfolio
    image: docker.io/ghostfolio/ghostfolio:${GHOSTFOLIO_TAG:-latest}
    init: true
    logging:
      driver: ${LOGGING_DRIVER:-local}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - ${PORT_GHOSTFOLIO_HTTP}:3333
    volumes:
      - ${CONFIG_DIR}/ghostfolio:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?connect_timeout=300"
      - ROOT_URL="https://ghostfolio.lan"
      - ENABLE_FEATURE_AUTH_OIDC=true
      - OIDC_ISSUER="https://auth.lan/application/o/ghostfolio/"
      - OIDC_CLIENT_ID="${OIDC_CLIENT_ID}"
      - OIDC_CLIENT_SECRET="${OIDC_CLIENT_SECRET}"
    labels:
      - caddy=ghostfolio.lan:443 ghostfolio.pi-rack-1.lan
      - caddy_ingress_network=container_bridge
      - caddy.reverse_proxy="{{upstreams 3333}}"
      - homepage.group=Personal Apps
      - homepage.name=Ghostfolio
      - homepage.icon=ghostfolio.svg
      - homepage.href=https://ghostfolio.lan
      - homepage.description=Portfolio Management
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - container_bridge

networks:
  container_bridge:
    external: true
