name: "caddy-pi_zero_1"

services:
  caddy:
    container_name: caddy-pi_zero_1
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    env_file:
      - .env
    volumes:
      - ./${CADDY_INSTANCE:-caddy}/config:/etc/caddy:ro
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/data:/data
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/config:/config
    labels:
      - homepage.name=Caddy Pi-Zero-1
      - homepage.description=Pi-Zero-1 Reverse Proxy
      - homepage.widget.url=http://${HOST_NAME}.${TAILNET}:${PORT_CADDY_ADMIN}