name: "actualbudget"

services:
  actual_server:
    container_name: actual_server
    image: docker.io/actualbudget/actual-server:${ACTUALBUDGET_TAG:-latest}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    ports:
      - ${PORT_ACTUAL_HTTP}:5006
    volumes:
      - ${CONFIG_DIR}/actual:/data
      - /etc/localtime:/etc/localtime:ro
      - ../../common/certs/trustca.crt:/certs/trustca.crt:ro
    environment:
      - TZ=${TZ}
      - ACTUAL_OPENID_DISCOVERY_URL=https://auth.lan/application/o/actual-budget/
      - ACTUAL_OPENID_CLIENT_ID=${ACTUAL_OPENID_CLIENT_ID}
      - ACTUAL_OPENID_CLIENT_SECRET=${ACTUAL_OPENID_CLIENT_SECRET}
      - ACTUAL_OPENID_SERVER_HOSTNAME=https://actual.lan
      - ACTUAL_OPENID_AUTH_METHOD=oauth2
    labels:
      - caddy=actual.lan:443 actual.pi-rack-1.lan
      - caddy_ingress_network=container_bridge
      - caddy.reverse_proxy="{{upstreams 5006}}"
      - homepage.group=Personal Apps
      - homepage.name=Actual Budget
      - homepage.icon=actual-budget.svg
      - homepage.href=https://actual.lan
      - homepage.description=Personal Finance
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - container_bridge

networks:
  container_bridge:
    external: true
