name: "caddy-attic_gateway"

services:
  caddy:
    container_name: caddy-attic_gateway
    env_file:
      - .env
    volumes:
      - ./${CADDY_INSTANCE:-caddy}/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/data:/data
      - ${CONFIG_DIR}/${CADDY_INSTANCE:-caddy}/config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - homepage.name=Caddy Attic-Gateway
      - homepage.description=Attic-Gateway Reverse Proxy
      - homepage.widget.url=http://${HOST_NAME}.${TAILNET}:${PORT_CADDY_ADMIN}